### ISSUE TITLE
quote not defined error?

### ISSUE THREAD

**Issue by BasharAG** [2018sjain/stock-predictions#1]
I installed the requirements, plugged in my Twitter keys, and then Iran the script, but after that it asked me to enter the quote, I did, and I got the following error:

```
Enter stock quote: snap
Traceback (most recent call last):
  File "stock-predict.py", line 76, in <module>
    quote = input('Enter stock quote: ').upper()
  File "<string>", line 1, in <module>
NameError: name 'snap' is not defined
```

**Comment by 2018sjain-zz** [comment]
This is most likely because you are running the code in a version of Python 2. To fix this just change `quote = input('Enter stock quote: ').upper()` to `quote = raw_input('Enter stock quote: ').upper()`. This way, Python will be expecting a string for the input.

**Comment by BasharAG** [comment]
Thanks that fixed it!
